//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjercicioParcial3Apl.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clases
    {
        public int id { get; set; }
        public int idhorario { get; set; }
        public int idprofesor { get; set; }
    
        public virtual horario horario { get; set; }
        public virtual niveles niveles { get; set; }
        public virtual profesores profesores { get; set; }
    }
}
