//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjercicioParcial3Apl.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cursoDetalle
    {
        public int id { get; set; }
        public int idcurso { get; set; }
        public string descripcion_corta { get; set; }
        public string descripcion_larga { get; set; }
    
        public virtual cursos cursos { get; set; }
    }
}
