//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjercicioParcial3Apl.WebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBAcademiaNEntities : DbContext
    {
        public DBAcademiaNEntities()
            : base("name=DBAcademiaNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<clases> clases { get; set; }
        public DbSet<cursoDetalle> cursoDetalle { get; set; }
        public DbSet<cursos> cursos { get; set; }
        public DbSet<grupos> grupos { get; set; }
        public DbSet<horario> horario { get; set; }
        public DbSet<niveles> niveles { get; set; }
        public DbSet<profesores> profesores { get; set; }
        public DbSet<secciones> secciones { get; set; }
    }
}
