//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjercicioParcial3Apl.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupos
    {
        public grupos()
        {
            this.horario = new HashSet<horario>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public int idcurso { get; set; }
        public string cantidad_personas { get; set; }
        public string tiempo_duracion { get; set; }
    
        public virtual cursos cursos { get; set; }
        public virtual ICollection<horario> horario { get; set; }
    }
}
