//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjercicioParcial3Apl.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class niveles
    {
        public niveles()
        {
            this.clases = new HashSet<clases>();
        }
    
        public int id { get; set; }
        public string NombreNivel { get; set; }
    
        public virtual ICollection<clases> clases { get; set; }
    }
}
